//! Zig bindings for rres (raylib resource format)
//! Auto-generated by scripts/generate_bindings.py

const std = @import("std");
const build_options = @import("build_options");

const c = if (build_options.enable_raylib) @cImport({
    @cInclude("raylib.h");
    @cInclude("rres.h");
    @cInclude("rres-raylib.h");
}) else @cImport({
    @cInclude("rres.h");
});

pub const rres_raylib = if (build_options.enable_raylib) c else void;

// Types
pub const rresFileHeader = c.rresFileHeader;
pub const rresResourceChunkInfo = c.rresResourceChunkInfo;
pub const rresResourceChunkData = c.rresResourceChunkData;
pub const rresResourceChunk = c.rresResourceChunk;
pub const rresResourceMulti = c.rresResourceMulti;
pub const rresDirEntry = c.rresDirEntry;
pub const rresCentralDir = c.rresCentralDir;
pub const rresFontGlyphInfo = c.rresFontGlyphInfo;

// Enums - Type-safe Zig wrappers with automatic conversion
pub const ResourceDataType = enum(c_uint) {
    null_ = 0,
    raw = 1,
    text = 2,
    image = 3,
    wave = 4,
    vertex = 5,
    font_glyphs = 6,
    link = 99,
    directory = 100,

    pub fn toCInt(self: @This()) c_uint {
        return @intFromEnum(self);
    }

    pub fn fromCInt(value: c_uint) @This() {
        return @enumFromInt(value);
    }
};

pub const CompressionType = enum(c_uint) {
    none = 0,
    rle = 1,
    deflate = 10,
    lz4 = 20,
    lzma2 = 30,
    qoi = 40,

    pub fn toCInt(self: @This()) c_uint {
        return @intFromEnum(self);
    }

    pub fn fromCInt(value: c_uint) @This() {
        return @enumFromInt(value);
    }
};

pub const EncryptionType = enum(c_uint) {
    none = 0,
    xor = 1,
    des = 10,
    tdes = 11,
    idea = 20,
    aes = 30,
    aes_gcm = 31,
    xtea = 40,
    blowfish = 50,
    rsa = 60,
    salsa20 = 70,
    chacha20 = 71,
    xchacha20 = 72,
    xchacha20_poly1305 = 73,

    pub fn toCInt(self: @This()) c_uint {
        return @intFromEnum(self);
    }

    pub fn fromCInt(value: c_uint) @This() {
        return @enumFromInt(value);
    }
};

pub const ErrorType = enum(c_uint) {
    success = 0,
    error_file_not_found,
    error_file_format,
    error_memory_alloc,

    pub fn toCInt(self: @This()) c_uint {
        return @intFromEnum(self);
    }

    pub fn fromCInt(value: c_uint) @This() {
        return @enumFromInt(value);
    }
};

pub const TextEncoding = enum(c_uint) {
    undefined_ = 0,
    utf8 = 1,
    utf8_bom = 2,
    utf16_le = 10,
    utf16_be = 11,

    pub fn toCInt(self: @This()) c_uint {
        return @intFromEnum(self);
    }

    pub fn fromCInt(value: c_uint) @This() {
        return @enumFromInt(value);
    }
};

pub const CodeLang = enum(c_uint) {
    undefined_ = 0,
    c,
    cpp,
    cs,
    lua,
    js,
    python,
    rust,
    zig,
    odin,
    jai,
    gdscript,
    glsl,

    pub fn toCInt(self: @This()) c_uint {
        return @intFromEnum(self);
    }

    pub fn fromCInt(value: c_uint) @This() {
        return @enumFromInt(value);
    }
};

pub const PixelFormat = enum(c_uint) {
    undefined_ = 0,
    uncomp_grayscale = 1,
    uncomp_gray_alpha,
    uncomp_r5g6b5,
    uncomp_r8g8b8,
    uncomp_r5g5b5a1,
    uncomp_r4g4b4a4,
    uncomp_r8g8b8a8,
    uncomp_r32,
    uncomp_r32g32b32,
    uncomp_r32g32b32a32,
    comp_dxt1_rgb,
    comp_dxt1_rgba,
    comp_dxt3_rgba,
    comp_dxt5_rgba,
    comp_etc1_rgb,
    comp_etc2_rgb,
    comp_etc2_eac_rgba,
    comp_pvrt_rgb,
    comp_pvrt_rgba,

    pub fn toCInt(self: @This()) c_uint {
        return @intFromEnum(self);
    }

    pub fn fromCInt(value: c_uint) @This() {
        return @enumFromInt(value);
    }
};

pub const VertexAttribute = enum(c_uint) {
    position = 0,
    texcoord1 = 10,
    texcoord2 = 11,
    texcoord3 = 12,
    texcoord4 = 13,
    normal = 20,
    tangent = 30,
    color = 40,
    index = 100,

    pub fn toCInt(self: @This()) c_uint {
        return @intFromEnum(self);
    }

    pub fn fromCInt(value: c_uint) @This() {
        return @enumFromInt(value);
    }
};

pub const VertexFormat = enum(c_uint) {
    ubyte = 0,
    byte,
    ushort,
    short,
    uint,
    int,
    hfloat,
    float,

    pub fn toCInt(self: @This()) c_uint {
        return @intFromEnum(self);
    }

    pub fn fromCInt(value: c_uint) @This() {
        return @enumFromInt(value);
    }
};

pub const FontStyle = enum(c_uint) {
    undefined_ = 0,
    regular,
    bold,
    italic,

    pub fn toCInt(self: @This()) c_uint {
        return @intFromEnum(self);
    }

    pub fn fromCInt(value: c_uint) @This() {
        return @enumFromInt(value);
    }
};

// Raw C enums (for direct C interop if needed)
pub const rresResourceDataType = c.rresResourceDataType;
pub const rresCompressionType = c.rresCompressionType;
pub const rresEncryptionType = c.rresEncryptionType;
pub const rresErrorType = c.rresErrorType;
pub const rresTextEncoding = c.rresTextEncoding;
pub const rresCodeLang = c.rresCodeLang;
pub const rresPixelFormat = c.rresPixelFormat;
pub const rresVertexAttribute = c.rresVertexAttribute;
pub const rresVertexFormat = c.rresVertexFormat;
pub const rresFontStyle = c.rresFontStyle;

// Functions with automatic enum conversion
// Functions without enum parameters (direct exports)
pub const rresLoadResourceChunk = c.rresLoadResourceChunk;
pub const rresUnloadResourceChunk = c.rresUnloadResourceChunk;
pub const rresLoadResourceMulti = c.rresLoadResourceMulti;
pub const rresUnloadResourceMulti = c.rresUnloadResourceMulti;
pub const rresLoadResourceChunkInfo = c.rresLoadResourceChunkInfo;
pub const rresLoadCentralDirectory = c.rresLoadCentralDirectory;
pub const rresUnloadCentralDirectory = c.rresUnloadCentralDirectory;
pub const rresGetDataType = c.rresGetDataType;
pub const rresGetResourceId = c.rresGetResourceId;
pub const rresComputeCRC32 = c.rresComputeCRC32;
pub const rresSetCipherPassword = c.rresSetCipherPassword;

// Helper extensions for working with enums

/// Helper to set compression type on ResourceChunkInfo using Zig enum
pub fn setCompressionType(info: *rresResourceChunkInfo, comp_type: CompressionType) void {
    info.compType = @intCast(comp_type.toCInt());
}

/// Helper to get compression type from ResourceChunkInfo as Zig enum
pub fn getCompressionType(info: rresResourceChunkInfo) CompressionType {
    return CompressionType.fromCInt(info.compType);
}

/// Helper to set encryption type on ResourceChunkInfo using Zig enum
pub fn setEncryptionType(info: *rresResourceChunkInfo, cipher_type: EncryptionType) void {
    info.cipherType = @intCast(cipher_type.toCInt());
}

/// Helper to get encryption type from ResourceChunkInfo as Zig enum
pub fn getEncryptionType(info: rresResourceChunkInfo) EncryptionType {
    return EncryptionType.fromCInt(info.cipherType);
}
